# Generated by Django 2.2 on 2019-12-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0002_auto_20191211_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answermodel',
            name='votes',
        ),
        migrations.AddField(
            model_name='answermodel',
            name='ans_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='ques_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='ans_img',
            field=models.ImageField(blank=True, null=True, upload_to='AnswerImg'),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='isaccept',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='ques_img',
            field=models.ImageField(blank=True, null=True, upload_to='QuestionImg'),
        ),
    ]
