# Generated by Django 2.2 on 2019-12-11 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0003_auto_20191211_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=255)),
                ('cat_desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='ques_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qna_app.CategoryModel'),
        ),
    ]
